version: '3.8'

services:
  app:
    build: .
    image: laravel-practice
    container_name: laravel-practice
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    volumes:
      - ".:/var/www/html"  
    extra_hosts:
      - host.docker.internal:host-gateway

      